/**
 * Proves the Flutter path end to end: a payload produced by the Dart package,
 * pushed through the shared clipboard codec, imported by the **real** built
 * plugin bundle against the strict Figma stand-in.
 *
 * The point is that the plugin needs no Flutter-specific code at all. A snapshot
 * is a snapshot, whether a Chrome DOM walk or a Flutter render-tree walk made it.
 *
 * The fixture is regenerated by `flutter test` in packages/flutter_capture, and
 * committed so this runs for contributors who do not have Flutter installed.
 *
 * Run with: node --test packages/figma-plugin/test/flutter-import.e2e.mjs
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createFigmaMock } from './figma-mock.mjs';
import { decodePayload } from '../../shared/src/payload.ts';

const here = path.dirname(fileURLToPath(import.meta.url));
const pluginBundle = path.join(here, '../dist/code.js');
const payloadPath = path.join(here, '../../flutter_capture/test/out/flutter-payload.c2d');

let mock;
let report;
let snapshot;

function walk(node, out = []) {
  out.push(node);
  for (const child of node.children ?? []) walk(child, out);
  return out;
}

const built = () => walk(mock.page).slice(1);
const texts = () => built().filter((n) => n.type === 'TEXT');

test.before(async () => {
  const payload = await fs.readFile(payloadPath, 'utf8');
  snapshot = await decodePayload(payload);

  // Exactly what the plugin's UI does before handing over to the sandbox.
  const images = {};
  for (const [id, asset] of Object.entries(snapshot.assets ?? {})) {
    const binary = Buffer.from(asset.data, 'base64');
    images[id] = new Uint8Array(binary);
  }
  const lean = {
    ...snapshot,
    assets: Object.fromEntries(
      Object.entries(snapshot.assets ?? {}).map(([id, a]) => [id, { ...a, data: '' }]),
    ),
  };

  mock = createFigmaMock();
  globalThis.figma = mock.figma;
  globalThis.__html__ = mock.html;
  // eslint-disable-next-line no-eval -- the bundle is an IIFE that reads globals
  (0, eval)(await fs.readFile(pluginBundle, 'utf8'));

  await mock.figma.ui.onmessage({
    type: 'import',
    snapshot: lean,
    images,
    options: { autoLayout: true, groupFrames: true, keepLinks: true },
  });

  const failed = mock.figma.__messages.find((m) => m.type === 'error');
  assert.ok(!failed, `the plugin rejected the Flutter payload: ${failed?.message}`);
  report = mock.figma.__messages.find((m) => m.type === 'done')?.report;
  assert.ok(report, 'the import never finished');
});

/* ------------------------------------------------------------------ tests */

test('a Flutter capture is a valid snapshot for the unmodified plugin', () => {
  assert.equal(snapshot.version, 1);
  assert.equal(snapshot.source.origin, 'flutter');
  assert.ok(snapshot.generator.includes('flutter'), `generator: ${snapshot.generator}`);
  assert.equal(report.skipped, 0, `layers were skipped: ${JSON.stringify(report.warnings)}`);
  assert.equal(report.frames, 1);
  assert.ok(report.layers > 5, `only ${report.layers} layers built`);
});

test('the widget text becomes real, editable Figma text', () => {
  const characters = texts().map((n) => n.characters);
  for (const expected of ['Hello Figma', 'Left', 'Right']) {
    assert.ok(
      characters.some((c) => c.includes(expected)),
      `"${expected}" never became a text layer. Got: ${JSON.stringify(characters)}`,
    );
  }
  // Not one of them is a rectangle with a picture of text on it.
  assert.equal(report.images, 0, 'the Flutter capture should contain no rasterised layers');
});

test('the heading keeps its size, weight and colour through the whole pipeline', () => {
  const heading = texts().find((n) => n.characters.includes('Hello Figma'));
  assert.ok(heading, 'the heading is missing');

  const sized = heading._ranges.filter((r) => r.what === 'setRangeFontSize');
  assert.ok(sized.length > 0, 'no font size was applied');

  const fills = heading._ranges.filter((r) => r.what === 'setRangeFills');
  assert.ok(fills.length > 0, 'no fill was applied');

  // The font Flutter asked for had to resolve to something Figma actually has.
  assert.ok(heading.fontName.family, 'the text node has no resolved font');
  for (const key of mock.figma.__state.loadedFonts) {
    assert.ok(!key.includes('undefined'), `bogus font loaded: ${key}`);
  }
});

test('the BoxDecoration becomes a real fill, corner radius and shadow', () => {
  const card = built().find(
    (n) => n.fills?.some((f) => f.type === 'SOLID' && Math.round(f.color.b * 255) === 245),
  );
  assert.ok(card, 'the decorated container never got its colour');
  assert.equal(Math.round(card.topLeftRadius), 12);
  assert.ok(
    card.effects.some((e) => e.type === 'DROP_SHADOW'),
    'the box shadow was lost',
  );
});

test('the LinearGradient survives as a Figma gradient paint', () => {
  const node = built().find((n) => n.fills?.some((f) => f.type === 'GRADIENT_LINEAR'));
  assert.ok(node, 'no gradient paint reached the canvas');
  const paint = node.fills.find((f) => f.type === 'GRADIENT_LINEAR');
  assert.equal(paint.gradientStops.length, 2);
  // Red on the left, blue on the right.
  assert.ok(paint.gradientStops[0].color.r > 0.9, 'the first stop is not red');
  assert.ok(paint.gradientStops[1].color.b > 0.9, 'the last stop is not blue');
});

test('Row and Column arrive as auto layout frames', () => {
  const vertical = built().find((n) => n.layoutMode === 'VERTICAL');
  assert.ok(vertical, 'the Column did not become auto layout');
  assert.equal(vertical.primaryAxisAlignItems, 'SPACE_BETWEEN');
  assert.equal(vertical.counterAxisAlignItems, 'CENTER');

  const horizontal = built().find((n) => n.layoutMode === 'HORIZONTAL');
  assert.ok(horizontal, 'the Row did not become auto layout');
  assert.equal(horizontal.primaryAxisAlignItems, 'CENTER');
});

test('the result is selected on the canvas, like any other import', () => {
  assert.equal(mock.page.children.length, 1);
  assert.equal(mock.page.selection.length, 1);
  assert.equal(mock.figma.__notifications.length, 1);
});
